apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: nenyeonyema/helloworld:latest
        ports:
        - containerPort: 5000
