apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32098
  selector:
    app: helloworld
