apiVersion: v1
kind: Pod
metadata:
  name: test-runner
spec:
  containers:
  - name: test-runner
    image: nenyeonyema/helloworld:latest
    command: ["pytest", "test_helloworld.py"]
  restartPolicy: Never
