apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: testing
spec:
  containers:
  - name: test-runner
    image: nenyeonyema/helloworld:latest
    command: ["pytest", "test_helloworld.py"]
  restartPolicy: Never
